2020-02-15 15:59:04,220 - __main__ - ERROR - <urlopen error Remote end closed connection without response>
2020-02-15 15:59:18,759 - __main__ - ERROR - <urlopen error timed out>
2020-02-15 15:59:48,844 - __main__ - ERROR - <urlopen error timed out>
2020-02-15 16:34:36,975 - __main__ - ERROR - <urlopen error Remote end closed connection without response>
2020-02-15 20:00:21,628 - __main__ - ERROR - <urlopen error Remote end closed connection without response>
2020-02-15 20:00:50,576 - __main__ - ERROR - <urlopen error timed out>
2020-02-15 20:00:53,709 - __main__ - ERROR - <urlopen error Remote end closed connection without response>
2020-02-15 20:01:53,264 - __main__ - ERROR - <urlopen error timed out>
2020-02-16 10:34:05,109 - __main__ - ERROR - <urlopen error Remote end closed connection without response>
2020-02-16 10:36:03,201 - __main__ - ERROR - <urlopen error Remote end closed connection without response>
2020-02-16 10:36:17,777 - __main__ - ERROR - <urlopen error timed out>
2020-02-16 10:36:17,791 - __main__ - ERROR - <urlopen error timed out>
2020-02-16 10:41:04,196 - __main__ - ERROR - <urlopen error [Errno 104] Connection reset by peer>
2020-02-16 10:41:04,257 - __main__ - ERROR - <urlopen error Remote end closed connection without response>
2020-02-16 10:46:57,064 - __main__ - ERROR - <urlopen error [Errno 104] Connection reset by peer>
2020-02-16 10:49:22,127 - __main__ - ERROR - <urlopen error Remote end closed connection without response>
2020-02-16 10:49:51,079 - __main__ - ERROR - <urlopen error timed out>
2020-02-16 10:49:54,217 - __main__ - ERROR - <urlopen error Remote end closed connection without response>
2020-02-16 10:51:12,936 - __main__ - ERROR - <urlopen error [Errno 104] Connection reset by peer>
2020-02-16 10:51:41,853 - __main__ - ERROR - <urlopen error timed out>
2020-02-16 10:51:41,867 - __main__ - ERROR - <urlopen error timed out>
2020-02-16 10:52:11,968 - __main__ - ERROR - <urlopen error timed out>
2020-02-16 13:40:17,489 - __main__ - ERROR - <urlopen error [Errno 111] Connection refused>
2020-02-16 13:40:17,491 - __main__ - ERROR - <urlopen error [Errno 111] Connection refused>
2020-02-16 13:40:24,704 - __main__ - ERROR - <urlopen error Remote end closed connection without response>
2020-02-16 13:40:44,372 - __main__ - ERROR - <urlopen error Remote end closed connection without response>
2020-02-16 13:43:36,472 - __main__ - ERROR - <urlopen error [Errno 111] Connection refused>
2020-02-16 13:43:51,842 - __main__ - ERROR - <urlopen error Remote end closed connection without response>
2020-02-16 13:44:06,469 - __main__ - ERROR - <urlopen error timed out>
2020-02-16 13:44:13,776 - __main__ - ERROR - <urlopen error Remote end closed connection without response>
2020-02-23 22:04:55,685 - __main__ - ERROR - <urlopen error [Errno 111] Connection refused>
2020-02-23 22:04:55,778 - __main__ - ERROR - <urlopen error [Errno 104] Connection reset by peer>
2020-02-23 22:05:25,679 - __main__ - ERROR - <urlopen error timed out>
2020-02-23 22:05:55,801 - __main__ - ERROR - <urlopen error timed out>
2020-02-26 18:33:03,107 - __main__ - ERROR - <urlopen error [Errno 111] Connection refused>
2020-02-26 18:33:04,243 - __main__ - ERROR - <urlopen error Remote end closed connection without response>
2020-02-26 18:33:18,658 - __main__ - ERROR - <urlopen error [Errno 113] No route to host>
2020-02-26 18:33:18,749 - __main__ - ERROR - <urlopen error Remote end closed connection without response>
2020-02-26 19:39:23,209 - __main__ - ERROR - <urlopen error [Errno 111] Connection refused>
2020-02-26 19:39:23,720 - __main__ - ERROR - <urlopen error Remote end closed connection without response>
2020-02-26 19:39:52,733 - __main__ - ERROR - <urlopen error timed out>
2020-02-26 19:39:52,747 - __main__ - ERROR - <urlopen error timed out>
2020-02-26 19:39:54,847 - __main__ - ERROR - <urlopen error Remote end closed connection without response>
2020-02-26 19:46:19,886 - __main__ - ERROR - <urlopen error [Errno 111] Connection refused>
2020-02-26 19:46:20,816 - __main__ - ERROR - <urlopen error Remote end closed connection without response>
2020-02-26 19:46:49,690 - __main__ - ERROR - <urlopen error timed out>
2020-02-26 19:46:57,030 - __main__ - ERROR - <urlopen error Remote end closed connection without response>
2020-02-26 19:50:39,666 - __main__ - ERROR - <urlopen error [Errno 111] Connection refused>
2020-02-26 19:50:40,791 - __main__ - ERROR - <urlopen error Remote end closed connection without response>
2020-02-26 19:51:09,665 - __main__ - ERROR - <urlopen error timed out>
2020-02-26 19:51:09,679 - __main__ - ERROR - <urlopen error timed out>
2020-02-26 19:51:39,765 - __main__ - ERROR - <urlopen error timed out>
2020-02-26 19:54:18,730 - __main__ - ERROR - <urlopen error [Errno 111] Connection refused>
2020-02-26 19:54:34,104 - __main__ - ERROR - <urlopen error Remote end closed connection without response>
2020-02-26 19:54:48,742 - __main__ - ERROR - <urlopen error timed out>
2020-02-26 19:55:05,717 - __main__ - ERROR - <urlopen error _ssl.c:1091: The handshake operation timed out>
2020-02-26 19:55:05,820 - __main__ - ERROR - <urlopen error [Errno 104] Connection reset by peer>
2020-02-27 00:03:52,325 - __main__ - ERROR - <urlopen error [Errno 104] Connection reset by peer>
2020-02-27 00:04:16,938 - __main__ - ERROR - <urlopen error Remote end closed connection without response>
2020-02-27 00:04:20,514 - __main__ - ERROR - <urlopen error timed out>
2020-02-27 00:04:20,529 - __main__ - ERROR - <urlopen error timed out>
2020-02-27 00:04:21,405 - __main__ - ERROR - <urlopen error [Errno 104] Connection reset by peer>
2020-02-27 00:05:09,794 - __main__ - ERROR - <urlopen error timed out>
2020-02-27 00:05:09,796 - __main__ - ERROR - <urlopen error timed out>
2020-02-27 00:05:43,397 - __main__ - ERROR - <urlopen error timed out>
2020-02-27 00:05:43,452 - __main__ - ERROR - <urlopen error timed out>
2020-02-27 00:06:07,747 - __main__ - ERROR - <urlopen error Remote end closed connection without response>
2020-02-27 00:06:26,638 - __main__ - ERROR - <urlopen error Remote end closed connection without response>
2020-02-27 00:06:32,584 - __main__ - ERROR - <urlopen error timed out>
2020-02-27 00:06:37,441 - __main__ - ERROR - <urlopen error Remote end closed connection without response>
2020-02-27 00:07:02,843 - __main__ - ERROR - <urlopen error timed out>
2020-02-27 00:07:31,720 - __main__ - ERROR - <urlopen error _ssl.c:1091: The handshake operation timed out>
2020-02-27 00:07:32,489 - __main__ - ERROR - <urlopen error [Errno 104] Connection reset by peer>
2020-02-27 00:08:01,938 - __main__ - ERROR - <urlopen error timed out>
2020-02-27 00:08:01,951 - __main__ - ERROR - <urlopen error timed out>
2020-02-27 00:08:20,870 - __main__ - ERROR - <urlopen error Remote end closed connection without response>
2020-02-27 00:08:32,098 - __main__ - ERROR - <urlopen error timed out>
2020-02-27 00:08:32,159 - __main__ - ERROR - <urlopen error timed out>
2020-02-27 00:08:32,171 - __main__ - ERROR - <urlopen error timed out>
2020-02-27 00:08:34,491 - __main__ - ERROR - <urlopen error Remote end closed connection without response>
2020-02-27 00:09:04,239 - __main__ - ERROR - <urlopen error _ssl.c:1091: The handshake operation timed out>
2020-02-27 00:09:14,854 - __main__ - ERROR - <urlopen error Remote end closed connection without response>
2020-02-27 00:11:42,089 - __main__ - ERROR - <urlopen error Remote end closed connection without response>
2020-02-27 00:12:09,314 - __main__ - ERROR - <urlopen error timed out>
2020-02-27 00:12:39,534 - __main__ - ERROR - <urlopen error timed out>
2020-02-27 00:12:39,600 - __main__ - ERROR - <urlopen error timed out>
2020-02-27 00:13:09,856 - __main__ - ERROR - <urlopen error timed out>
2020-02-27 00:13:44,443 - __main__ - ERROR - <urlopen error timed out>
2020-02-27 00:13:57,908 - __main__ - ERROR - Remote end closed connection without response
2020-02-27 00:14:28,105 - __main__ - ERROR - <urlopen error timed out>
2020-02-27 00:14:44,647 - __main__ - ERROR - <urlopen error Remote end closed connection without response>
2020-02-27 00:15:11,926 - __main__ - ERROR - <urlopen error timed out>
2020-02-27 00:15:11,953 - __main__ - ERROR - <urlopen error timed out>
2020-02-27 00:15:42,202 - __main__ - ERROR - <urlopen error timed out>
2020-02-27 00:16:12,461 - __main__ - ERROR - <urlopen error timed out>
2020-02-27 00:16:12,481 - __main__ - ERROR - <urlopen error timed out>
2020-02-27 00:16:42,745 - __main__ - ERROR - <urlopen error timed out>
2020-02-27 00:17:03,725 - __main__ - ERROR - <urlopen error Remote end closed connection without response>
2020-02-27 00:17:16,302 - __main__ - ERROR - <urlopen error timed out>
2020-02-27 00:17:28,069 - __main__ - ERROR - <urlopen error Remote end closed connection without response>
2020-02-27 00:17:47,562 - __main__ - ERROR - <urlopen error timed out>
2020-02-27 00:17:47,578 - __main__ - ERROR - <urlopen error timed out>
2020-02-27 00:18:17,882 - __main__ - ERROR - <urlopen error timed out>
2020-02-27 00:18:33,364 - __main__ - ERROR - <urlopen error Remote end closed connection without response>
2020-02-27 00:18:48,135 - __main__ - ERROR - <urlopen error timed out>
2020-02-27 00:19:20,756 - __main__ - ERROR - <urlopen error Remote end closed connection without response>
2020-02-27 00:20:16,795 - __main__ - ERROR - <urlopen error timed out>
2020-02-27 00:20:16,811 - __main__ - ERROR - <urlopen error timed out>
2020-02-27 00:20:25,517 - __main__ - ERROR - <urlopen error Remote end closed connection without response>
2020-02-27 00:20:47,036 - __main__ - ERROR - <urlopen error timed out>
2020-02-27 00:20:47,092 - __main__ - ERROR - <urlopen error timed out>
2020-02-27 00:21:17,341 - __main__ - ERROR - <urlopen error timed out>
2020-02-27 00:21:17,344 - __main__ - ERROR - <urlopen error timed out>
2020-02-27 00:21:17,374 - __main__ - ERROR - <urlopen error timed out>
2020-02-27 00:22:30,168 - __main__ - ERROR - <urlopen error timed out>
2020-02-27 00:22:30,187 - __main__ - ERROR - <urlopen error timed out>
2020-02-27 00:22:30,202 - __main__ - ERROR - <urlopen error timed out>
2020-02-27 00:22:47,558 - __main__ - ERROR - <urlopen error Remote end closed connection without response>
2020-02-27 00:23:27,560 - __main__ - ERROR - The read operation timed out
2020-02-27 00:24:09,767 - __main__ - ERROR - <urlopen error timed out>
2020-02-27 00:24:09,822 - __main__ - ERROR - <urlopen error timed out>
2020-02-27 00:24:40,022 - __main__ - ERROR - <urlopen error timed out>
2020-02-27 00:24:40,073 - __main__ - ERROR - <urlopen error timed out>
2020-02-27 00:25:10,295 - __main__ - ERROR - <urlopen error timed out>
2020-02-27 00:25:10,338 - __main__ - ERROR - <urlopen error timed out>
2020-02-27 00:25:14,104 - __main__ - ERROR - <urlopen error [Errno 104] Connection reset by peer>
2020-02-27 00:25:40,580 - __main__ - ERROR - <urlopen error timed out>
2020-02-27 00:25:40,592 - __main__ - ERROR - <urlopen error timed out>
2020-02-27 00:26:10,777 - __main__ - ERROR - <urlopen error timed out>
2020-02-27 00:26:10,815 - __main__ - ERROR - <urlopen error timed out>
2020-02-27 00:26:10,838 - __main__ - ERROR - <urlopen error timed out>
2020-02-27 00:26:53,078 - __main__ - ERROR - <urlopen error _ssl.c:1091: The handshake operation timed out>
2020-02-27 00:27:23,290 - __main__ - ERROR - <urlopen error timed out>
2020-02-27 00:27:23,406 - __main__ - ERROR - <urlopen error timed out>
2020-02-27 00:27:46,755 - __main__ - ERROR - The read operation timed out
